language: go

go:
  - 1.12.x

env:
  global:
    - GO111MODULE=on
    - GOFLAGS='-mod vendor'
    - PATH=${TRAVIS_BUILD_DIR}/bin:${PATH}

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s vX.Y.Z

script:
  - golangci-lint run
  - go test -v -race ./...
